[workspace]
members = ["lab_optimistic_lock"]
resolver = "2"

[workspace.dependencies]
tokio = "1.37.0"
sqlx = "0.7.4"
testcontainers-modules ="0.4.2"
testcontainers ="0.16.7"
uuid = "1.8.0"
test-context = "0.3.0"
